version: '3'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nlp8
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nlp8db
    ports:
      - "5432:5432"

  fastapi:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    restart: always
    command: npm start
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true

volumes:
    postgres_data: 