version: '3'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nlp8
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nlp8db
    ports:
      - "5432:5432"

  fastapi:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    restart: always
    command: npm start
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true

  airflow:
    image: apache/airflow:2.3.3
    command: bash -c "airflow db upgrade && airflow webserver"
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://nlp8:postgres@db:5432/nlp8db
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/airflow/dags
      - ./airflow/logs:/airflow/logs
      - ./airflow/plugins:/airflow/plugins

volumes:
    postgres_data: 