version: '3'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nlp8
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nlp8db

  fastapi:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
    postgres_data: 